/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SplitPayRouteImport } from './routes/split-pay'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OptimizeRouteImport } from './routes/optimize'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinkUpiRouteImport } from './routes/link-upi'
import { Route as LinkBankRouteImport } from './routes/link-bank'
import { Route as HealthClaimsRouteImport } from './routes/health-claims'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitPayRoute = SplitPayRouteImport.update({
  id: '/split-pay',
  path: '/split-pay',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizeRoute = OptimizeRouteImport.update({
  id: '/optimize',
  path: '/optimize',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkUpiRoute = LinkUpiRouteImport.update({
  id: '/link-upi',
  path: '/link-upi',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkBankRoute = LinkBankRouteImport.update({
  id: '/link-bank',
  path: '/link-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthClaimsRoute = HealthClaimsRouteImport.update({
  id: '/health-claims',
  path: '/health-claims',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/health-claims': typeof HealthClaimsRoute
  '/link-bank': typeof LinkBankRoute
  '/link-upi': typeof LinkUpiRoute
  '/login': typeof LoginRoute
  '/optimize': typeof OptimizeRoute
  '/signup': typeof SignupRoute
  '/split-pay': typeof SplitPayRoute
  '/subscriptions': typeof SubscriptionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/health-claims': typeof HealthClaimsRoute
  '/link-bank': typeof LinkBankRoute
  '/link-upi': typeof LinkUpiRoute
  '/login': typeof LoginRoute
  '/optimize': typeof OptimizeRoute
  '/signup': typeof SignupRoute
  '/split-pay': typeof SplitPayRoute
  '/subscriptions': typeof SubscriptionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/health-claims': typeof HealthClaimsRoute
  '/link-bank': typeof LinkBankRoute
  '/link-upi': typeof LinkUpiRoute
  '/login': typeof LoginRoute
  '/optimize': typeof OptimizeRoute
  '/signup': typeof SignupRoute
  '/split-pay': typeof SplitPayRoute
  '/subscriptions': typeof SubscriptionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/health-claims'
    | '/link-bank'
    | '/link-upi'
    | '/login'
    | '/optimize'
    | '/signup'
    | '/split-pay'
    | '/subscriptions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/health-claims'
    | '/link-bank'
    | '/link-upi'
    | '/login'
    | '/optimize'
    | '/signup'
    | '/split-pay'
    | '/subscriptions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/health-claims'
    | '/link-bank'
    | '/link-upi'
    | '/login'
    | '/optimize'
    | '/signup'
    | '/split-pay'
    | '/subscriptions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  HealthClaimsRoute: typeof HealthClaimsRoute
  LinkBankRoute: typeof LinkBankRoute
  LinkUpiRoute: typeof LinkUpiRoute
  LoginRoute: typeof LoginRoute
  OptimizeRoute: typeof OptimizeRoute
  SignupRoute: typeof SignupRoute
  SplitPayRoute: typeof SplitPayRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split-pay': {
      id: '/split-pay'
      path: '/split-pay'
      fullPath: '/split-pay'
      preLoaderRoute: typeof SplitPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimize': {
      id: '/optimize'
      path: '/optimize'
      fullPath: '/optimize'
      preLoaderRoute: typeof OptimizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link-upi': {
      id: '/link-upi'
      path: '/link-upi'
      fullPath: '/link-upi'
      preLoaderRoute: typeof LinkUpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link-bank': {
      id: '/link-bank'
      path: '/link-bank'
      fullPath: '/link-bank'
      preLoaderRoute: typeof LinkBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-claims': {
      id: '/health-claims'
      path: '/health-claims'
      fullPath: '/health-claims'
      preLoaderRoute: typeof HealthClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  HealthClaimsRoute: HealthClaimsRoute,
  LinkBankRoute: LinkBankRoute,
  LinkUpiRoute: LinkUpiRoute,
  LoginRoute: LoginRoute,
  OptimizeRoute: OptimizeRoute,
  SignupRoute: SignupRoute,
  SplitPayRoute: SplitPayRoute,
  SubscriptionsRoute: SubscriptionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
